name: Code Analysis

on:
  push:
    branches: ["*"]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew clean build

      - name: SonarCloud Analysis
        # Put all flags on one line to avoid "Task '-Dsonar.projectKey=...' not found"
        run: ./gradlew sonarqube -Dsonar.projectKey=aditonorman_eshop -Dsonar.organization=aditonorman -Dsonar.login=${{ secrets.SONAR_TOKEN }}
